# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

project_name: ska
before:
  hooks:
  - go mod tidy
builds:
- env:
  - CGO_ENABLED=0
  goos:
  - linux
  - windows
  - darwin
  goarch:
  - amd64
  - arm
  - arm64
  ldflags:
  - -s -w -X cmd.version={{.Version}}
release:
  prerelease: auto
nfpms:
- file_name_template: '{{ .ProjectName }}_{{ .Arch }}'
  maintainer: hello@g-c.dev
  homepage: https://ska.g-c.dev
  description: >-
    SKA is a CLI and Library to scaffold, maintain and update from upstream blueprint your projects.
  license: MIT
  formats:
  - deb
  - rpm
  - apk
  bindir: /usr/bin
  section: utils
  contents:
  - src: ./LICENSE
    dst: /usr/share/doc/nfpm/copyright
    file_info:
      mode: 0644
sboms:
- artifacts: archive
brews:
- repository:
    owner: gchiesa
    name: homebrew-ska
    branch: main
    token: "{{ .Env.SKA_HOMEBREW_TOKEN }}"
  # yamllint disable-line rule:comments rule:line-length
  url_template: https://github.com/gchiesa/ska/releases/download/{{ .Tag }}/{{ .ArtifactName }}
  commit_author:
    name: Giuseppe Chiesa
    email: mail@giuseppechiesa.it
  directory: Formula
  homepage: https://github.com/gchiesa/ska
  description: >-
    SKA is a CLI and Library to scaffold, maintain and update from upstream blueprint your projects.
  license: MIT
archives:
- wrap_in_directory: true
  format_overrides:
  - goos: windows
    format: zip
checksum:
  name_template: checksums.txt
snapshot:
  name_template: '{{ .Tag }}-next'
changelog:
  disable: true
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - '^*.md:'